//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Barricade.Process
{
	using System;
    using Barricade.Logic;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Spel
	{
		public virtual void Verplaats(Pion pion, IVeld bestemming)
		{
			throw new System.NotImplementedException();
		}

		public virtual List<IVeld> MogelijkeZetten(Pion pion)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Verplaats()
		{
			throw new System.NotImplementedException();
		}

	}
}

