//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Barricade.Logic.Velden
{
    public class Startveld : VeldBase
	{
        public override bool MagBarricade { get { return false; } }
        public override bool MagPionErlangs { get { return true; } }
        public override bool MagPion(Pion pion)
        {
            return false;
        }
	    public override bool Plaats(Pion pion)
        {
            Pionnen.Add(pion);
            return true;
        }

	    public Speler Speler { get; set; }
	}
}

