//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Logic
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Barricade
	{
		public virtual Veld Veld
		{
			get;
			set;
		}

		public virtual void Verplaats(Veld bestemming)
		{
			throw new System.NotImplementedException();
		}

	}
}

