//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Logic
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Finishveld : IVeld
	{
	    public object IsDorp { get; set; }
	    public object IsPlaatsbaar { get; set; }
	    public IEnumerable<IVeld> IVeld { get; set; }
	    public IEnumerable<Pion> Pion { get; set; }
	}
}

