//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Logic
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IVeld 
	{
		object IsDorp { get;set; }

		object IsPlaatsbaar { get;set; }

		IEnumerable<IVeld> IVeld { get;set; }

		List<Pion> Pionen { get; private set; }

	}
}

