//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Logic
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IVeld 
	{
		bool IsDorp { get;set; }

		bool IsPlaatsbaar { get;set; }

		IEnumerable<IVeld> Buren { get; }

		IEnumerable<Pion> Pion { get;set; }

	}
}

