//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Logic
{
	using Process;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Pion
	{
		public virtual IVeld IVeld
		{
			get;
			set;
		}

		public virtual Speler Speler
		{
			get;
			private set;
		}

		public virtual List<Barricade.Modeling::Logic::IVeld> MogelijkeZetten()
		{
			throw new System.NotImplementedException();
		}

		public virtual bool Verplaats(IVeld bestemming)
		{
			throw new System.NotImplementedException();
		}

	}
}

