//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Logic
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Speler
	{
	    public char Name { get; private set; }

	    public virtual List<Pion> Pionen
		{
			get;
			private set;
		}

		public virtual Spel Spel
		{
			get;
			set;
		}

		public virtual Startveld Startveld
		{
			get;
			set;
		}

        public Speler(char name)
        {
            Name = name;
            Pionen = new List<Pion>();
        }
	}
}

