//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Logic
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Spel
	{
        public virtual List<Speler> Spelers
        {
            get; private set;
        }

        public Spel()
        {
            Spelers = new List<Speler>();
        }

	}
}

