//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Logic
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Speler
	{
		public virtual List<Pion> Pionen
		{
			get;
			private set;
		}

		public virtual Spelbord Spelbord
		{
			get;
			set;
		}

		public virtual List<Startveld> Startveld
		{
			get;
			set;
		}

        public Speler()
        {
            Pionen = new List<Pion>();
            Startveld = new List<Startveld>();
        }

	}
}

