//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Logic
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Spelbord
	{
	    private List<Speler> spelers = new List<Speler>();


        public List<Speler> GetSpelers()
        {
            return spelers; 
        }

        public void AddSpeler(Speler s)
        {
            spelers.Add(s);
        }

	}
}

