//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Barricade.Logic
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Startveld : VeldBase
	{

        public new bool PlaatsPion(Pion pion)
        {
            VerwijderPion(pion);
            Pionnen.Add(pion);
            return true;
        }

	    public Speler Speler { get; set; }
	}
}

