//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Logic
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Veld : VeldBase
	{
	    public bool StandaardBarricade = false;

		public virtual bool MagBarricade
		{
			get;
			set;
		}

		public virtual Barricade Barricade
		{
			get;
			set;
		}

        public new bool PlaatsPion(Pion pion)
        {
             VerwijderPion(pion);

            //staat al iets op, sla deze pion
            if (Pionnen.Any())
            {
                Pionnen.First().IVeld = Pionnen.First().Speler.Startveld;
                Pionnen.First().Speler.Startveld.PlaatsPion(Pionnen.First());
                Pionnen = new List<Pion>();
            }

            Pionnen.Add(pion);
            return true;
        }

	}
}

