//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Logic
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Veld : IVeld
	{
		public virtual bool MagBarricade
		{
			get;
			set;
		}

		public virtual Barricade Barricade
		{
			get;
			set;
		}

	}
}

